version: '3.7'
services:
  nginx:
      image: nginx:1.19.2-alpine
      hostname: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./eoffice-fullchain.pem:/opt/eoffice-fullchain.pem
        - ./eoffice-key.pem:/opt/eoffice-key.pem
      ports:
        - "443:443"
        - "80:80"