version: '3'
services:
  hub:
    image: codecamplao/eoffice-hub:v1.0.2
    container_name: eoffice-hub
    hostname: hub
    restart: always
    extra_hosts:
      - "db.local:10.1.1.79"
      - "postgres.local:10.1.1.79"
      - "log.local:10.1.1.79"
    ports:
      - "5000:80"
    networks: 
      - ccnetwork
  nginx:
      image: nginx:1.19.2-alpine
      container_name: eoffice-proxy
      hostname: proxy
      restart: always
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./eoffice-fullchain.pem:/opt/eoffice-fullchain.pem
        - ./eoffice-key.pem:/opt/eoffice-key.pem
      ports:
        - "443:443"
        - "80:80"
      networks: 
      - ccnetwork
      depends_on:
      - hub
networks: 
  ccnetwork: